# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Calendar

on:
  schedule:
    # every monday at at 1pm
    - cron: 0 12 * * 1
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run regenerate

    - name: Commit Calendar
      uses: EndBug/add-and-commit@v7
      with:
        add: 'TAB_EVENTS.ics'
        message: 'update calendar'
        push: 'origin main --force'
